---
- name: Check if rustup is available.
  ansible.builtin.command:
    cmd: rustup --version
  ignore_errors: true
  register: ru_version_result
  changed_when: false

- name: Install Rust and it's toolchain.
  when: ru_version_result is failed
  block:
    # - name: Install rustup.
    #   become: true
    #   community.general.snap:
    #     name: rustup
    #     channel: stable
    #     classic: true
    #     state: present

    - name: Download rustup installation script.
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-install.sh
        mode: "0644"

    - name: Run installation script in non-interactive mode.
      ansible.builtin.script:
        cmd: /tmp/rustup-install.sh -y --no-modify-path
