---
- name: Setup Hashicorp's apt repository.
  when: hashitools_setup_vault or  hashitools_setup_consul or hashitools_setup_nomad
  ansible.builtin.include_tasks: repo.yml

- name: Setup Nomad and it's dependencies.
  when: hashitools_setup_vault
  ansible.builtin.include_tasks: vault.yml

- name: Setup Consul and it's dependencies.
  when: hashitools_setup_consul
  ansible.builtin.include_tasks: consul.yml

- name: Setup Nomad and it's dependencies.
  when: hashitools_setup_nomad
  ansible.builtin.include_tasks: nomad.yml
