---
- name: Install Java
  hosts: 127.0.0.1
  connection: local
  roles:
    # - role: dev
    # - role: java
    # - role: docker
    - role: hashitools
      vars:
        hashitools_setup_nomad: true
