---
- name: Install Development tools on devboxes.
  hosts: devboxs
  roles:
    - role: general
    # - role: java
    # - role: docker
    # - role: hashitools
    #   vars:
    #     hashitools_setup_consul: true
    #     hashitools_setup_nomad: true
    # - role: opentofu
    # - role: go
    # - role: python
    # - role: rust
