---
- name: Update Development tools on devboxes.
  hosts: devboxs
  vars:
    role:
    ansible_connection: local
  tasks:
    - ansible.builtin.include_role:
        name: "{{ role }}" # set via CLI as -e role=go
        tasks_from: "{{ tasks | default('main') }}.yml"
